[project]
name = "shop-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.13,<2.0",
    "flask>=3.1,<4.0",
    "opencv-python-headless>=4.10,<5.0",
    "pytesseract>=0.3.13",
    "sqlalchemy>=2.0,<3.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
